server:
  port: 8888
#  http2:
#    enabled: true
#  undertow:
#    io-threads: 16
#    worker-threads: 256
#    buffer-size: 1024
#    direct-buffers: true
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: demo
management:
  endpoint:
    nacos-discovery:
      enabled: true
